### ISSUE TITLE
rose deployment: tolerate restarting/ add cron job

### ISSUE THREAD

**Issue by chunhualiao** [chunhualiao/freeCompilerCamp#101]
service is down.

**Comment by chunhualiao** [comment]
From Anjia: 

I've updated the config file 'docker-compose.yml' in the repo on AWS. Now it will start the server automatically after rebooting.

Basically an option 'restart: always' is added to all three services in PWC. It takes a few minutes to let PWC come alive after restarting.  

Since we have changed to the approach using Git Pages and PWC instead of original everything in one place idea, 'docker-compose' should be used to start/stop the server. In short, go to /home/ubuntu/play-with-compiler and run 'docker-compose up -d' to start. I'll update the wiki tonight.

**Comment by ouankou** [comment]
Solved in the commit https://github.com/freeCompilerCamp/play-with-compiler/commit/6d771b0133478afe2765b3df7b81a4c8cadde8fa#diff-4e5e90c6228fd48698d074241c2ba760.
