### ISSUE TITLE
add a new GPU backend server

### ISSUE THREAD

**Issue by chunhualiao** [chunhualiao/freeCompilerCamp#104]
The design is a web server + multiple docker-in-docker servers.

**Comment by chunhualiao** [comment]
@ouankou  when ready, please connect to the gpu instance for this tutorial: http://freecompilercamp.org/llvm-openmp-build/ Thanks.

**Comment by ouankou** [comment]
The GPU is supported by the commit https://github.com/freeCompilerCamp/play-with-compiler/commit/33a336efa7f1caf950c1bb1f7f370f27f2368abd. Now it's always enabled in the backend. However, on the host without NVIDIA GPU, while creating a container, it will throw the following error and the creation fails.

```
docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].
```

Therefore, we must use a environment variable to determine whether this parameter should be used.

**Comment by ouankou** [comment]
A config flag is added to control whether the GPU should be enabled in containers. By default, it's set to false. On a server with GPU, we must change the flag to true before starting the FreeCC service.

https://github.com/freeCompilerCamp/play-with-compiler/commit/7e7aa003e4d879fefd2403f41dabf475c59b406e
