### ISSUE TITLE
FreeCC site still using Ubuntu 16.04 image as default

### ISSUE THREAD

**Issue by vec4** [chunhualiao/freeCompilerCamp#120]
I am getting the following error when running the practical tool with the provided input for the complex types practical:

```
> "/usr/include/c++/5/bits/c++0x_warning.h", line 32: catastrophic error: #error
>           directive: This file requires compiler and library support for the
>           ISO C++ 2011 standard. This support must be enabled with the
>           -std=c++11 or -std=gnu++11 compiler options.
>   #error This file requires compiler and library support \
>    ^
> 
> Errors in Processing Input File: throwing an instance of "frontend_failed"exception due to syntax errors detected in the input code
```

The tool builds properly without any errors. Even more interestingly, it works fine without any errors on my localhost PWC. On my localhost, I use `freecompilercamp/pwc:full`, which uses Ubuntu 18.04 and g++ version 7.5.0.

I try compile the input code separately with g++ and get the same error. Maybe the image on AWS doesn't have a gcc version new enough to support the C++11 standard? After some digging around, I found that the FreeCC site uses Ubuntu 16.04 with g++ version 5.4.0 as default when no image is provided. This version of g++ requires explicit use of the `-std=c++11` whereas newer versions of g++ (6.1+) use C++14 by default. Hence the error.

From https://github.com/chunhualiao/freeCompilerCamp/issues/76, the default image should be `freecompilercamp/pwc:full` with Ubuntu 18.04, but it seems it still uses 16.04 (and so, an older g++). The only ROSE tutorial that has 18.04 is the traversal one, since it explicitly uses the rose-debug image.

**Comment by ouankou** [comment]
By checking the created sandboxes, I can confirm that they are created based on `freecompilercamp/pwc:1.0`, which has been removed from the PWC list. It's similar with the issue happened before. Last time the image used incorrectly was `franela:dind` that was not on the list as well. It seems that PWC switched to an outdated config at some point.

I'll check this bug and maybe modify the way calling default image. At the mean time, we could specify the docker image for each new tutorial as workaround.

**Comment by vec4** [comment]
Sounds good, thanks!

**Comment by ouankou** [comment]
Now the default docker image is set from the training website. It will automatically specify an image if the user didn't do it. Please check the commit https://github.com/freeCompilerCamp/freecompilercamp.github.io/commit/a4ff6d9bfc07fb0d03a5280dcf31eac5bd6925f8.

For the PWC side, the issue is caused by `pwd` container, which works as a controller as PWC to receive requests and create sandboxes. I checked the settings inside that container and everything looks fine including the GO source code. The inspection report of that container has been saved. If this issue happens again, we could inspect `pwd` again to see the difference.

**Comment by vec4** [comment]
Thanks for the fix Anjia! The ROSE tutorials without defined images are using 18.04 now. I will close the issue and re-open in the case that it occurs again.
