### ISSUE TITLE
New Tutorial: Advanced AST Construction

### ISSUE THREAD

**Issue by vec4** [chunhualiao/freeCompilerCamp#122]
(See #107)

Tutorial for some more advanced program transformations using the AST, based on Chapter 32 of the tutorial PDF. We have a small tutorial on modifying the AST that serves as a great intro to how to do a basic program transformation. The purpose of this one would be to cover more complicated AST modifications. e.g, adding functions, assignments, etc.

This will be a part of 3-4, possibly more, tutorials on program transformations and optimizations, mostly from the chapter of the same name in the tutorial PDF, but also from some sections of the wikibook.

**Comment by vec4** [comment]
Since the existing AST modification tutorial focuses on the high-level interface, I will instead focus this tutorial around using the low-level interface.

**Comment by chunhualiao** [comment]
The current recommedation is to use SageInterface and SageBuilder for all
translation.   Low level interface is being phased out.

**Comment by vec4** [comment]
Ah, ok, thanks for letting me know!

**Comment by chunhualiao** [comment]
I think the current tutorial looks very good. 

Two suggestions: 
1. You can split the tutorial into 3: expression, declaration , and function

2. builder functions such as buildVariableDeclaration() do take a scope parameter, though the scope stack will be used if not specified.   The recommended practice is to always pass the scope parameter explicitly to reduce mistakes. You may want to mention this and revise your examples to use explicit scope parameters.

**Comment by chunhualiao** [comment]
There is one existing tutorial building a function call: http://freecompilercamp.org/rose-ast-modification/ 
Please check if it can be moved into your section "Program Transformation and Optimization". 

Free free to rename it to be more specific, consistent with other similar tutorials.

**Comment by vec4** [comment]
Thanks for the feedback! I appreciate it.

I will update the tutorial to mention and use the explicit scope parameters. With regards to point 1, do you mean 3 different tutorials, i.e., 3 different ones on the landing page? I think this might be too fine-grained (in my opinion) - what if we did a two-part tutorial like the following:

- AST Modification - Declarations and Expressions
- AST Modification - Functions and Function Calls

These would be separate tutorials on the landing page. That way, we could move the existing tutorial on AST modification about building function calls to this section, but also keep it more coarse-grained and still avoid putting everything in one tutorial. I want to include a few other tutorials about program transformation (inliner/outliner, etc.) in this section as well.

**Comment by chunhualiao** [comment]
your granularity is better. Thanks.

**Comment by vec4** [comment]
Great, I will make the changes soon. Thanks!
