### ISSUE TITLE
Change default logo

### ISSUE THREAD

**Issue by almishra** [chunhualiao/freeCompilerCamp#74]
There is a need to create a logo for FreeCC.
Also currently thumbnail logo still shows docker logo (found in images/simple-logo.png)

**Comment by ouankou** [comment]
The  default logo settings has been changed (https://github.com/freeCompilerCamp/freecompilercamp.github.io/commit/d6898da5e13fa913d1e189641dd84fb30e4e78b0).

Two image files are involved. `/images/favicon.ico` is used for the logo on the tab of browser. `images/simple-logo.png` is used for the thumbnail logo when we share a page.
They are updated in the commit https://github.com/freeCompilerCamp/freecompilercamp.github.io/commit/7309ef7c8d82966c6987b156729ca75c7525f26d. For now, I create a logo from https://favicon.io/emoji-favicons/atom-symbol/. We may create another more suitable one later.
