### ISSUE TITLE
update the docker image to use Ubuntu 18.04

### ISSUE THREAD

**Issue by chunhualiao** [chunhualiao/freeCompilerCamp#76]
Be careful to get the version of ROSE with the example bug.

**Comment by ouankou** [comment]
A new docker image based on Ubuntu 18.04 has been created and pushed to DockerHub.
Please check the following link.
https://hub.docker.com/repository/docker/freecompilercamp/pwc

In the tags, `latest` refers to the latest image that contains everything including LLVM and ROSE. At this moment, `latest` = `18.04` = `1.1`.

`18.04` and `16.04` indicate the different base Ubuntu OS version.

`1.1` and `1.0` indicate the conventional version number. Currently `1.1` = `18.04`, `1.0` = `16.04`.

**Comment by chunhualiao** [comment]
@ouankou please test/deploy the new docker using latest version of ROSE on Ubuntu 18.04.

**Comment by ouankou** [comment]
Now we provide the following docker images for sandbox. They are all based on Ubuntu 18.04.

- `freecompilercamp/pwc:full`: it contains both LLVM 10 and ROSE. If no image is specified by user, this one is used by default.
- `freecompilercamp/pwc:llvm10`: it contains only LLVM 10.
- `freecompilercamp/pwc:rose`: it contains only a release version of ROSE.
- `freecompilercamp/pwc:rose-debug`: it contains a debug build of ROSE, `-O0` is used by default.
- `freecompilercamp/pwc:rose-bug`: it contains an old version of ROSE that has a loop stride bug.

https://hub.docker.com/repository/docker/freecompilercamp/pwc
